services:
  # redis container
  redis:
    image: redis:8.6.2
    expose:
      - "6379"
  
  # postgres container
  postgres-db:
    image: postgres:18.3
    expose:
      - "5432"
  
  # backend api container
  express-api:
    depends_on:
      - postgres-db
      - redis
    build: ./backend
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://localhost:6379 # use redis container hostname
      - DB_USER=postgres
      - DB_NAME=notes_db
      - DB_HOST=localhost
      - DB_PORT=5432
    secrets:
      - database-password

  # react build container
  react-build-frontend:
    depends_on:
      - express-api
    build: ./frontend
    ports:
      - "3006:3000"

secrets:
  database-password:
    file: ./db-password.txt
