services:
  # redis container
  redis:
    image: redis:8.6.2
    expose:
      - 6379
  
  # postgres container
  postgres_db:
    image: postgres:18.3
    expose:
      - 5432
    environment: # must have postgres env variables to initialize postgres database
      POSTGRES_USER: user1
      POSTGRES_DB: notes_db
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
    secrets:
      - database_password
    volumes: # persistent volume
      - all-notes-data:/var/lib/postgresql
  
  # backend api container
  express_api:
    depends_on:
      - postgres_db
      - redis
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      DB_USER: user1
      DB_NAME: notes_db
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_PASSWORD: /run/secrets/database_password
    secrets:
      - database_password

  # react build container
  react-build-frontend:
    depends_on:
      - express_api
    build: ./frontend
    ports:
      - "3000:3000"

secrets:
  database_password:
    file: ./db-password.txt

volumes:
  all-notes-data:
